//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing_Info
    {
        public long Id { get; set; }
        public long Company_Id { get; set; }
        public string Bill_VC_No { get; set; }
        public long User_Id { get; set; }
        public Nullable<decimal> Billing_Amount { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> Discount_Amount { get; set; }
        public Nullable<decimal> Transport { get; set; }
        public string Tag_Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Billing_Date { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
    }
}
