//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Master
    {
        public Company_Master()
        {
            this.Billing_Info = new HashSet<Billing_Info>();
            this.Branch_Master = new HashSet<Branch_Master>();
            this.City_Master = new HashSet<City_Master>();
            this.Contact_Info = new HashSet<Contact_Info>();
            this.Customers = new HashSet<Customer>();
            this.Emp_Common_Master = new HashSet<Emp_Common_Master>();
            this.FinancialYears = new HashSet<FinancialYear>();
            this.GoDown_Master = new HashSet<GoDown_Master>();
            this.GoDown_Region = new HashSet<GoDown_Region>();
            this.Ledger_Master = new HashSet<Ledger_Master>();
            this.Ledger_Group = new HashSet<Ledger_Group>();
            this.Login_Master = new HashSet<Login_Master>();
            this.Payment_Info = new HashSet<Payment_Info>();
            this.Quation_Master = new HashSet<Quation_Master>();
            this.Role_Master = new HashSet<Role_Master>();
            this.Stock_Group = new HashSet<Stock_Group>();
            this.Stock_Item = new HashSet<Stock_Item>();
            this.Stock_Master = new HashSet<Stock_Master>();
            this.Stock_Category = new HashSet<Stock_Category>();
            this.Suppliers = new HashSet<Supplier>();
            this.Tax_Deduction_Master = new HashSet<Tax_Deduction_Master>();
            this.Tax_Master = new HashSet<Tax_Master>();
            this.UnitMasters = new HashSet<UnitMaster>();
            this.Purchase_Master = new HashSet<Purchase_Master>();
            this.Sales_Master = new HashSet<Sales_Master>();
            this.Receipt_Info = new HashSet<Receipt_Info>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Alias_Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phoe_No { get; set; }
        public string Reg_No { get; set; }
        public string Tin_No { get; set; }
        public string Pan_No { get; set; }
        public string WebSite { get; set; }
        public string Pin_Code { get; set; }
        public long Country_Id { get; set; }
        public long State_Id { get; set; }
        public Nullable<long> City_Id { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual ICollection<Billing_Info> Billing_Info { get; set; }
        public virtual ICollection<Branch_Master> Branch_Master { get; set; }
        public virtual ICollection<City_Master> City_Master { get; set; }
        public virtual ICollection<Contact_Info> Contact_Info { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Emp_Common_Master> Emp_Common_Master { get; set; }
        public virtual ICollection<FinancialYear> FinancialYears { get; set; }
        public virtual ICollection<GoDown_Master> GoDown_Master { get; set; }
        public virtual ICollection<GoDown_Region> GoDown_Region { get; set; }
        public virtual ICollection<Ledger_Master> Ledger_Master { get; set; }
        public virtual ICollection<Ledger_Group> Ledger_Group { get; set; }
        public virtual ICollection<Login_Master> Login_Master { get; set; }
        public virtual ICollection<Payment_Info> Payment_Info { get; set; }
        public virtual ICollection<Quation_Master> Quation_Master { get; set; }
        public virtual ICollection<Role_Master> Role_Master { get; set; }
        public virtual ICollection<Stock_Group> Stock_Group { get; set; }
        public virtual ICollection<Stock_Item> Stock_Item { get; set; }
        public virtual ICollection<Stock_Master> Stock_Master { get; set; }
        public virtual ICollection<Stock_Category> Stock_Category { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Tax_Deduction_Master> Tax_Deduction_Master { get; set; }
        public virtual ICollection<Tax_Master> Tax_Master { get; set; }
        public virtual ICollection<UnitMaster> UnitMasters { get; set; }
        public virtual Country_State Country_State { get; set; }
        public virtual Country_State Country_State1 { get; set; }
        public virtual ICollection<Purchase_Master> Purchase_Master { get; set; }
        public virtual ICollection<Sales_Master> Sales_Master { get; set; }
        public virtual ICollection<Receipt_Info> Receipt_Info { get; set; }
    }
}
