//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Master_TaxDetails
    {
        public long Id { get; set; }
        public long Pur_Id { get; set; }
        public string Pur_VC_No { get; set; }
        public long Tax_Id { get; set; }
        public Nullable<decimal> Tax_Rate { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    }
}
