//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Master
    {
        public Purchase_Master()
        {
            this.Purchase_Return = new HashSet<Purchase_Return>();
            this.Purchase_Master_Tra = new HashSet<Purchase_Master_Tra>();
        }
    
        public long Id { get; set; }
        public long Company_Id { get; set; }
        public string Pur_VC_No { get; set; }
        public long Supplier_Id { get; set; }
        public System.DateTime DATE { get; set; }
        public long Fncl_Year_Id { get; set; }
        public Nullable<decimal> Discount_Amount { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<decimal> Paid_Amount { get; set; }
        public Nullable<decimal> Bal_Amount { get; set; }
        public bool Is_Refered { get; set; }
        public string Refered_Type { get; set; }
        public Nullable<long> Refered_Id { get; set; }
        public bool Is_Bill_Gen { get; set; }
        public string Remarks { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
        public virtual ICollection<Purchase_Return> Purchase_Return { get; set; }
        public virtual ICollection<Purchase_Master_Tra> Purchase_Master_Tra { get; set; }
    }
}
