//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Return
    {
        public Purchase_Return()
        {
            this.Purchase_Return_Tra = new HashSet<Purchase_Return_Tra>();
        }
    
        public long Id { get; set; }
        public long Purchase_Id { get; set; }
        public System.DateTime DATE { get; set; }
        public string PurRet_VC_No { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<decimal> Discount_Amount { get; set; }
        public int Return_Type { get; set; }
        public string Remarks { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public long Supplier_Id { get; set; }
    
        public virtual ICollection<Purchase_Return_Tra> Purchase_Return_Tra { get; set; }
        public virtual Purchase_Master Purchase_Master { get; set; }
    }
}
