//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quation_Master
    {
        public Quation_Master()
        {
            this.Quation_Master_Tra = new HashSet<Quation_Master_Tra>();
        }
    
        public long Id { get; set; }
        public long Company_Id { get; set; }
        public long Customer_Id { get; set; }
        public string Quation_VC_No { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Quation_Type { get; set; }
        public string Tag_Type { get; set; }
        public bool Is_Approved { get; set; }
        public long Approved_By { get; set; }
        public long Fncl_Year_Id { get; set; }
        public string Remarks { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
        public virtual ICollection<Quation_Master_Tra> Quation_Master_Tra { get; set; }
    }
}
