//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Info
    {
        public Receipt_Info()
        {
            this.Receipt_Info_Tra = new HashSet<Receipt_Info_Tra>();
        }
    
        public long Id { get; set; }
        public long Company_Id { get; set; }
        public string VC_No { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public long Customer_Id { get; set; }
        public string Receipt_Type { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public string Account_No { get; set; }
        public string Bank_Name { get; set; }
        public string IFSC_Code { get; set; }
        public System.DateTime Receipt_Date { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Cheque_No { get; set; }
        public string Remarks { get; set; }
        public bool Bill_By_Bill { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
        public virtual ICollection<Receipt_Info_Tra> Receipt_Info_Tra { get; set; }
    }
}
