//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Order
    {
        public long Id { get; set; }
        public int Company_Id { get; set; }
        public Nullable<long> Customer_Id { get; set; }
        public string Sales_Order_VC_No { get; set; }
        public long Sales_Person { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public System.DateTime Order_Date { get; set; }
        public System.DateTime Request_Delivery_Date { get; set; }
        public string Remarks { get; set; }
        public bool Is_Refered { get; set; }
        public string Refered_Type { get; set; }
        public Nullable<long> Refered_Id { get; set; }
        public bool Is_DeliveryNote { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    }
}
