//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Master
    {
        public Sales_Master()
        {
            this.Sales_Return = new HashSet<Sales_Return>();
            this.Sales_Master_Tra = new HashSet<Sales_Master_Tra>();
        }
    
        public long Id { get; set; }
        public long Company_Id { get; set; }
        public long Customer_Id { get; set; }
        public System.DateTime DATE { get; set; }
        public string Sales_VC_No { get; set; }
        public bool Is_Bill_Gen { get; set; }
        public long Fncl_Year_Id { get; set; }
        public Nullable<decimal> Discount_Amount { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<decimal> Receipt_Amount { get; set; }
        public Nullable<decimal> Bal_Amount { get; set; }
        public bool Is_Refered { get; set; }
        public string Refered_Type { get; set; }
        public Nullable<long> Refered_Id { get; set; }
        public string Remarks { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
        public virtual ICollection<Sales_Return> Sales_Return { get; set; }
        public virtual ICollection<Sales_Master_Tra> Sales_Master_Tra { get; set; }
    }
}
