//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Item
    {
        public long Id { get; set; }
        public long Company_Id { get; set; }
        public string Item_Code { get; set; }
        public string Name { get; set; }
        public string Alias_Name { get; set; }
        public long Group_Id { get; set; }
        public long Category_Id { get; set; }
        public long Unit_Id { get; set; }
        public string Sufix_SerialNo { get; set; }
        public string Prefix_SerialNo { get; set; }
        public int Starting_SerialNo { get; set; }
        public decimal Min_Qty { get; set; }
        public string Image_Url { get; set; }
        public bool Is_Auto { get; set; }
        public string Remarks { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
    }
}
