//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitMaster
    {
        public long Id { get; set; }
        public long Company_Id { get; set; }
        public string Name { get; set; }
        public string Alias_Name { get; set; }
        public string Unit_Volume { get; set; }
        public long Group_Id { get; set; }
        public Nullable<int> No_of_Decimal { get; set; }
        public Nullable<decimal> Ratio1 { get; set; }
        public Nullable<decimal> Ratio2 { get; set; }
        public string Remarks { get; set; }
        public long Created_By { get; set; }
        public long Modified_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
    }
}
